security:
  basic:
    enabled: false
management:
  security:
    enabled: false

server:
  port: 8080
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#  data:
#    rest:
#      basePath: /api

  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/web3
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
